# Generated by Django 4.2.7 on 2023-11-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('full_text', models.TextField(max_length=5500, verbose_name='Текст')),
                ('date', models.DateField(verbose_name='Дата Публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/img/')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
            },
        ),
    ]
