# Generated by Django 4.2.7 on 2023-11-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bio',
            options={'verbose_name': 'Биография', 'verbose_name_plural': 'Биографии'},
        ),
        migrations.AlterField(
            model_name='bio',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='full_text',
            field=models.TextField(max_length=5500, verbose_name='Текст'),
        ),
    ]
