# Generated by Django 4.2.7 on 2023-11-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_alter_bio_options_alter_bio_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/img/'),
        ),
    ]
