# Generated by Django 4.2.7 on 2023-12-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book2_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('subject', models.CharField(max_length=150, verbose_name='Тема сообщения')),
                ('full_text', models.TextField(max_length=1000, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
