# Generated by Django 4.2.7 on 2023-12-03 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book3'),
    ]

    operations = [
        migrations.AddField(
            model_name='book3',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
